
name: release

on: 
    push:
        tags:
            - 'v*'

jobs:
    create_config_tar:
        name: Create the configuration tarball
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Create the tarball
              run: |
                  tar -C config/ -cv . -f packages.redbeardlab.com.tar

            - name: Create the Release
              uses: actions/create-release@v1
              id: create_release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  draft: false

            - name: Upload Configuration Tarball
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./packages.redbeardlab.com.tar
                  asset_name: packages.redbeardlab.com.config.tar
                  asset_content_type: application/tar

            - name: Create the docker container
              run: |
                  docker build . -t redbeardlab/packages:${{ github.event.release.tag_name }}

            - name: Login into dockerhub
              run: |
                  docker login -p ${{ secrets.DOCKERHUB_TOKEN}} -u siscia

            - name: push into dockerhub
              run: |
                  docker push redbeardlab/packages:${{ github.event.release.tag_name }}

                    
